export interface Quote {
  text: string;
  emoji: string;
  category: "Vibrant" | "Steady" | "Serene";
}

// Mapped from morning_quotes.txt:
// Power & Ambition → Vibrant, Resilience & Growth → Steady, Calm & Wisdom & Gratitude → Serene
export const QUOTES: Quote[] = [
  // 🔥 POWER & CONFIDENCE → Vibrant
  { emoji: "🔥", text: "You were not born to fit in. You were born to stand out.", category: "Vibrant" },
  { emoji: "⚡", text: "Your potential is limitless. The only ceiling is the one you build.", category: "Vibrant" },
  { emoji: "🦁", text: "Walk into the room like you own it — because one day, you will.", category: "Vibrant" },
  { emoji: "💎", text: "Confidence is not 'they will like me.' Confidence is 'I'll be fine if they don't.'", category: "Vibrant" },
  { emoji: "🏔️", text: "The mountain doesn't care how tired you are. Neither does greatness.", category: "Vibrant" },
  { emoji: "⚔️", text: "You have survived every hard day so far. Your record speaks for itself.", category: "Vibrant" },
  { emoji: "🌪️", text: "Be the energy you wish to encounter.", category: "Vibrant" },
  { emoji: "🦅", text: "Eagles don't lose sleep over the opinions of pigeons.", category: "Vibrant" },
  { emoji: "🔱", text: "Stop asking for permission to be extraordinary.", category: "Vibrant" },
  { emoji: "🚀", text: "You are not a drop in the ocean. You are the entire ocean in a drop.", category: "Vibrant" },
  { emoji: "💥", text: "Your story isn't over. It's just getting to the good part.", category: "Vibrant" },
  { emoji: "🛡️", text: "No one is coming to save you. And that is the most empowering truth there is.", category: "Vibrant" },
  { emoji: "🌟", text: "Shine so bright that others need sunglasses just to look at your future.", category: "Vibrant" },
  { emoji: "🐉", text: "You are the author. The pen is in your hand. Write something worth reading.", category: "Vibrant" },
  { emoji: "💡", text: "The world needs the specific thing only you can offer. Don't deprive it.", category: "Vibrant" },
  { emoji: "🎯", text: "Doubt kills more dreams than failure ever will.", category: "Vibrant" },
  { emoji: "🦊", text: "Be the version of yourself that the younger you would be amazed by.", category: "Vibrant" },
  { emoji: "🌊", text: "The tide doesn't ask for permission to rise. Neither should you.", category: "Vibrant" },
  { emoji: "🗡️", text: "Your voice has a frequency the world has never heard. Use it.", category: "Vibrant" },
  { emoji: "🏹", text: "Aim so high that even your misses are impressive.", category: "Vibrant" },
  { emoji: "🔮", text: "You are already everything you've been waiting to become.", category: "Vibrant" },
  { emoji: "🦋", text: "Transform so completely that even your past self wouldn't recognize you.", category: "Vibrant" },
  { emoji: "🎖️", text: "Comfort zones are beautiful places where nothing ever grows.", category: "Vibrant" },
  { emoji: "🌙", text: "Even on your darkest night, you are someone else's guiding star.", category: "Vibrant" },
  { emoji: "🔑", text: "The door to your dreams opens from the inside.", category: "Vibrant" },
  { emoji: "💪", text: "Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't.", category: "Vibrant" },
  { emoji: "🌅", text: "Every sunrise is a reminder that you got another chance to be unstoppable.", category: "Vibrant" },
  { emoji: "🏆", text: "Winners don't wait for chances. They take them.", category: "Vibrant" },
  { emoji: "⚡", text: "Your energy introduces you before your name does.", category: "Vibrant" },
  { emoji: "🌠", text: "Chase greatness quietly. Let your results scream.", category: "Vibrant" },

  // 🚀 AMBITION & DRIVE → Vibrant
  { emoji: "🚀", text: "The vision in your head is a promise you owe to the world.", category: "Vibrant" },
  { emoji: "🏆", text: "Average is a choice. Excellence is a discipline.", category: "Vibrant" },
  { emoji: "🎯", text: "Work so hard in silence that success makes the noise for you.", category: "Vibrant" },
  { emoji: "⚡", text: "Your dreams don't expire. But your excuses should.", category: "Vibrant" },
  { emoji: "🌅", text: "Today's sunrise is an invitation to outdo yesterday's version of yourself.", category: "Vibrant" },
  { emoji: "🔥", text: "Don't just set goals. Build systems that make them inevitable.", category: "Vibrant" },
  { emoji: "💰", text: "Wealth starts in the mind before it shows in the bank account.", category: "Vibrant" },
  { emoji: "🌍", text: "Think bigger than your current environment allows.", category: "Vibrant" },
  { emoji: "⏰", text: "Your morning routine is your competitive advantage.", category: "Vibrant" },
  { emoji: "🎪", text: "The ordinary life is not for extraordinary people. Choose your path.", category: "Vibrant" },
  { emoji: "🦁", text: "The lion doesn't need the approval of the sheep.", category: "Vibrant" },
  { emoji: "📊", text: "Measure your effort, not just your outcomes. The numbers will follow.", category: "Vibrant" },
  { emoji: "🧭", text: "Never let the noise of others' opinions drown your inner compass.", category: "Vibrant" },
  { emoji: "🏗️", text: "Build an empire while they're still sleeping.", category: "Vibrant" },
  { emoji: "💡", text: "Every great achievement was once an 'impossible' idea someone refused to abandon.", category: "Vibrant" },
  { emoji: "🌠", text: "Shoot for the stars. Even a miss lands you among them.", category: "Vibrant" },
  { emoji: "🗺️", text: "You don't need the whole road. Just see the next step clearly.", category: "Vibrant" },
  { emoji: "🎲", text: "Fortune favors the bold. Be bolder than yesterday.", category: "Vibrant" },
  { emoji: "🔓", text: "Unlock the door to your future. The key is already in your hands.", category: "Vibrant" },
  { emoji: "🛸", text: "Your ambition is not arrogance. It's a responsibility.", category: "Vibrant" },
  { emoji: "🎖️", text: "Outwork everyone. Then outwork yourself.", category: "Vibrant" },
  { emoji: "🌊", text: "Make waves. Still water doesn't move anything.", category: "Vibrant" },
  { emoji: "⚔️", text: "Your goals deserve the best fighter in you — every single day.", category: "Vibrant" },
  { emoji: "🏁", text: "Obsession isn't a flaw when the cause is worthy.", category: "Vibrant" },
  { emoji: "💎", text: "Diamonds are made under pressure. So are legacies.", category: "Vibrant" },
  { emoji: "🌙", text: "When you wake up with purpose, you already won half the battle.", category: "Vibrant" },
  { emoji: "🧱", text: "Build your empire one brick per day. Consistency beats intensity.", category: "Vibrant" },
  { emoji: "🌋", text: "Dormant volcanoes are still volcanoes. Don't mistake your patience for weakness.", category: "Vibrant" },
  { emoji: "🎯", text: "Discipline is choosing your goals over your impulses. Every single morning.", category: "Vibrant" },
  { emoji: "🦋", text: "What you're building now will be someone else's inspiration someday.", category: "Vibrant" },

  // 🌱 GROWTH & PROGRESS → Steady
  { emoji: "🌱", text: "Every expert was once a beginner who refused to quit.", category: "Steady" },
  { emoji: "📈", text: "Progress, not perfection. Every step forward counts.", category: "Steady" },
  { emoji: "🌿", text: "You don't have to be great to start, but you have to start to be great.", category: "Steady" },
  { emoji: "🔭", text: "Dream big. Start small. Act now.", category: "Steady" },
  { emoji: "🧗", text: "The climb is hard, but the view is worth every step.", category: "Steady" },
  { emoji: "🌾", text: "Plant seeds of effort today. Harvest the rewards of tomorrow.", category: "Steady" },
  { emoji: "📚", text: "The person who reads every day walks in the shoes of a thousand people.", category: "Steady" },
  { emoji: "🎓", text: "Every lesson you learn is armor you never have to take off.", category: "Steady" },
  { emoji: "🌻", text: "Grow through what you go through.", category: "Steady" },
  { emoji: "🛤️", text: "The road to mastery is paved with consistent, quiet effort.", category: "Steady" },
  { emoji: "🧩", text: "Every skill you build is a piece of a puzzle that only you can complete.", category: "Steady" },
  { emoji: "🏗️", text: "Build slowly, build deeply. Great things are never rushed.", category: "Steady" },
  { emoji: "🌈", text: "After every storm, you become a little more unbreakable.", category: "Steady" },
  { emoji: "🔬", text: "Curiosity is the most powerful tool in your arsenal. Stay curious.", category: "Steady" },
  { emoji: "🌍", text: "The more you learn, the more the world expands for you.", category: "Steady" },
  { emoji: "🪴", text: "Small disciplines repeated with consistency lead to great achievements.", category: "Steady" },
  { emoji: "✏️", text: "You are always a rough draft. Keep editing.", category: "Steady" },
  { emoji: "🧠", text: "The brain that learns every day never grows old.", category: "Steady" },
  { emoji: "🦋", text: "Change is not loss. Change is becoming.", category: "Steady" },
  { emoji: "🏋️", text: "Every rep, every page, every hour — it all compounds.", category: "Steady" },
  { emoji: "🌱", text: "Growth is uncomfortable because you're outgrowing who you were.", category: "Steady" },
  { emoji: "🎯", text: "One good habit, consistently practiced, can rewrite your entire future.", category: "Steady" },
  { emoji: "⏳", text: "Time is not wasted when it is spent becoming.", category: "Steady" },
  { emoji: "🌀", text: "Reinvention is not starting over. It's leveling up.", category: "Steady" },
  { emoji: "📖", text: "Your biography is still being written. Make it worth reading.", category: "Steady" },
  { emoji: "🌤️", text: "Every morning is a new chapter. What will you write today?", category: "Steady" },
  { emoji: "🔧", text: "Fix yourself quietly. Emerge loudly.", category: "Steady" },
  { emoji: "🌊", text: "Ride the wave of change — or it will ride you.", category: "Steady" },
  { emoji: "🎵", text: "Like a song, life gets better with practice and repetition.", category: "Steady" },
  { emoji: "🪞", text: "The best investment you'll ever make is in the person in the mirror.", category: "Steady" },

  // ⚔️ RESILIENCE → Steady
  { emoji: "🌊", text: "The storm didn't break you. It revealed how deeply rooted you are.", category: "Steady" },
  { emoji: "🔥", text: "You've already survived the worst days of your life. That's not nothing.", category: "Steady" },
  { emoji: "🌑", text: "Even the darkest night will end. And the sun will rise.", category: "Steady" },
  { emoji: "⚙️", text: "Pressure is a privilege. It means you're worth testing.", category: "Steady" },
  { emoji: "🦷", text: "Grit is the quiet kind of brave.", category: "Steady" },
  { emoji: "🧱", text: "You were built for this moment, even when it doesn't feel like it.", category: "Steady" },
  { emoji: "🏜️", text: "Even in the desert, roots know how to find water.", category: "Steady" },
  { emoji: "🌪️", text: "Let the chaos forge you. Gold doesn't come from calm fires.", category: "Steady" },
  { emoji: "⛓️", text: "Break the chains quietly. The world will notice the results.", category: "Steady" },
  { emoji: "🔩", text: "The strongest steel is forged in the hottest fire.", category: "Steady" },
  { emoji: "🌋", text: "You erupted once. They called it a breakdown. You call it a breakthrough.", category: "Steady" },
  { emoji: "🌬️", text: "Bend like the reed in the wind. You will not break.", category: "Steady" },
  { emoji: "🐚", text: "The pearl doesn't form without the irritation. Neither does resilience.", category: "Steady" },
  { emoji: "⛰️", text: "Fall seven times. Stand eight. That math always works out.", category: "Steady" },
  { emoji: "🧨", text: "What couldn't destroy you has become part of your power.", category: "Steady" },
  { emoji: "🌿", text: "Roots grow stronger under pressure. So do you.", category: "Steady" },
  { emoji: "🪨", text: "Be like stone — shaped by time, unbroken by it.", category: "Steady" },
  { emoji: "💧", text: "Water doesn't force its way. It finds a path. So will you.", category: "Steady" },
  { emoji: "🎭", text: "Your scars are proof that you showed up when it mattered.", category: "Steady" },
  { emoji: "🌃", text: "The night is darkest just before dawn. Hold on.", category: "Steady" },
  { emoji: "⚓", text: "You are your own anchor. Stay grounded.", category: "Steady" },
  { emoji: "🌾", text: "The field that was scorched last season blooms most brilliantly next spring.", category: "Steady" },
  { emoji: "🔑", text: "Every setback is a setup for the most incredible comeback.", category: "Steady" },
  { emoji: "🪖", text: "Survivors don't just endure. They evolve.", category: "Steady" },
  { emoji: "🌙", text: "The moon doesn't apologize for the darkness. It just keeps shining.", category: "Steady" },
  { emoji: "🧲", text: "What you've been through has made you magnetic to the right outcomes.", category: "Steady" },
  { emoji: "🔥", text: "Let the pain be fuel. You have an infinite tank.", category: "Steady" },
  { emoji: "🦅", text: "The bird that flies into the headwind rises highest.", category: "Steady" },
  { emoji: "🏹", text: "Every wound is a point of entry for light.", category: "Steady" },
  { emoji: "🌏", text: "You are not a problem to be solved. You are a force to be witnessed.", category: "Steady" },

  // 🍃 CALM & MINDFULNESS → Serene
  { emoji: "🌅", text: "This morning is a clean slate. Breathe. Begin.", category: "Serene" },
  { emoji: "🍃", text: "Peace is not something you find. It's something you practice.", category: "Serene" },
  { emoji: "🌊", text: "Be still. The answers often arrive in the silence.", category: "Serene" },
  { emoji: "☁️", text: "Let thoughts pass like clouds. You are the sky, not the storm.", category: "Serene" },
  { emoji: "🧘", text: "Your mind is the most powerful room in any building. Keep it clean.", category: "Serene" },
  { emoji: "🌿", text: "You don't have to rush. The right things will not miss you.", category: "Serene" },
  { emoji: "🪷", text: "A single breath, taken fully, can reset everything.", category: "Serene" },
  { emoji: "🌙", text: "Rest is not giving up. Rest is preparing for the next move.", category: "Serene" },
  { emoji: "🌸", text: "Not every moment needs to be productive. Some moments just need to be lived.", category: "Serene" },
  { emoji: "🌾", text: "Slow down enough to notice how beautiful the ordinary is.", category: "Serene" },
  { emoji: "🐢", text: "Patience is not passive. It's an active trust in the right timing.", category: "Serene" },
  { emoji: "🌤️", text: "The mind that is at peace can see clearly. Protect yours.", category: "Serene" },
  { emoji: "🍵", text: "Start the morning slowly. The world will wait for someone moving with intention.", category: "Serene" },
  { emoji: "🌫️", text: "Let go of what you can't control. Hold tightly to who you are.", category: "Serene" },
  { emoji: "🦢", text: "Elegance is born from stillness.", category: "Serene" },
  { emoji: "🧊", text: "Cool mind. Warm heart. That is the formula.", category: "Serene" },
  { emoji: "🌍", text: "The earth doesn't rush to bloom. Neither should you.", category: "Serene" },
  { emoji: "🌺", text: "Tend to your inner garden with the same care you'd give the most precious flowers.", category: "Serene" },
  { emoji: "🌙", text: "Tonight, let it all go. Tomorrow, begin again — lighter.", category: "Serene" },
  { emoji: "🪟", text: "Open the window of your mind. Let fresh thoughts in.", category: "Serene" },
  { emoji: "🍂", text: "Release what no longer serves you. Make room for what does.", category: "Serene" },
  { emoji: "🌊", text: "Flow. Don't force.", category: "Serene" },
  { emoji: "🌟", text: "The quieter you become, the more you can hear what truly matters.", category: "Serene" },
  { emoji: "🕊️", text: "Stillness is not emptiness. It is fullness in disguise.", category: "Serene" },
  { emoji: "🌱", text: "This moment is enough. You are enough. Right now.", category: "Serene" },

  // 🦉 WISDOM & PERSPECTIVE → Serene
  { emoji: "🦉", text: "The wisest thing you can do is know what you don't know.", category: "Serene" },
  { emoji: "📜", text: "Your life is a library. Every experience adds a volume.", category: "Serene" },
  { emoji: "🌀", text: "Time spent in reflection is never wasted.", category: "Serene" },
  { emoji: "🔭", text: "Zoom out. The problem that fills your screen today is a footnote in your story.", category: "Serene" },
  { emoji: "🌊", text: "The wise surfer doesn't fight the wave. They read it.", category: "Serene" },
  { emoji: "🌿", text: "What you give your attention to, you become.", category: "Serene" },
  { emoji: "⏳", text: "Ten years from now you'll wish you'd started today.", category: "Serene" },
  { emoji: "🌐", text: "The world reveals itself to those who ask better questions.", category: "Serene" },
  { emoji: "🧭", text: "Direction is more important than speed.", category: "Serene" },
  { emoji: "🪞", text: "What bothers you in others is often a mirror of what you're working on in yourself.", category: "Serene" },
  { emoji: "🌱", text: "The tree that bends in the storm stands longer than the one that resists.", category: "Serene" },
  { emoji: "🎭", text: "Life doesn't happen to you. It happens through you.", category: "Serene" },
  { emoji: "🔮", text: "The future belongs to those who prepare for it today.", category: "Serene" },
  { emoji: "🏔️", text: "Every mountain has a path. You just have to find the one that's yours.", category: "Serene" },
  { emoji: "🌤️", text: "Clarity comes to those who are brave enough to sit with the question.", category: "Serene" },
  { emoji: "🗝️", text: "Wisdom is knowing which doors to open and which ones to walk past.", category: "Serene" },
  { emoji: "🌸", text: "Not everything that weighs you down is yours to carry.", category: "Serene" },
  { emoji: "🎵", text: "Listen more than you speak. The most important things whisper.", category: "Serene" },
  { emoji: "🌊", text: "Go with the current when you can. Swim against it only when it matters.", category: "Serene" },
  { emoji: "📐", text: "The quality of your decisions determines the quality of your life.", category: "Serene" },
  { emoji: "🌙", text: "Some nights are made for thinking. Some days are made for doing. Know the difference.", category: "Serene" },
  { emoji: "🌍", text: "Gratitude and anxiety cannot occupy the same mind.", category: "Serene" },
  { emoji: "🦢", text: "The most elegant response to adversity is composure.", category: "Serene" },
  { emoji: "🧩", text: "You don't need to see the whole picture to place the next piece.", category: "Serene" },
  { emoji: "🌺", text: "Comparison is the thief of joy and the enemy of originality.", category: "Serene" },
  { emoji: "⚖️", text: "Balance is not a state you reach. It's a practice you return to.", category: "Serene" },
  { emoji: "🔬", text: "Question everything — especially your own assumptions.", category: "Serene" },
  { emoji: "🌲", text: "The deeper your roots, the taller you can grow.", category: "Serene" },
  { emoji: "💧", text: "Gentleness is not weakness. It is a refined form of strength.", category: "Serene" },
  { emoji: "🪐", text: "You are a small part of something vast and beautiful. That's a comfort, not a diminishment.", category: "Serene" },

  // ☀️ GRATITUDE & JOY → Serene
  { emoji: "☀️", text: "Today is a gift. That is why it's called the present.", category: "Serene" },
  { emoji: "🌸", text: "There is beauty in ordinary moments for those who choose to look.", category: "Serene" },
  { emoji: "🙏", text: "Gratitude turns what you have into enough.", category: "Serene" },
  { emoji: "🌊", text: "Every breath is an act of grace. Don't waste a single one.", category: "Serene" },
  { emoji: "💛", text: "The simple things — sunlight, laughter, warmth — are the irreplaceable things.", category: "Serene" },
  { emoji: "🌿", text: "You woke up today. Millions didn't. That alone is reason enough to try.", category: "Serene" },
  { emoji: "🎶", text: "Joy is not something to be chased. It's something to be noticed.", category: "Serene" },
  { emoji: "🌅", text: "Good mornings begin with a grateful heart, not a perfect plan.", category: "Serene" },
  { emoji: "🦋", text: "Happiness is not a destination. It's a way of travelling.", category: "Serene" },
  { emoji: "🍋", text: "Even the sour things have a purpose. They make the sweet sweeter.", category: "Serene" },
  { emoji: "🌻", text: "Find something tiny to be grateful for. It always leads to something bigger.", category: "Serene" },
  { emoji: "🌺", text: "Celebrate small wins. They are the foundation of great ones.", category: "Serene" },
  { emoji: "🤍", text: "You are loved more than you know and stronger than you feel.", category: "Serene" },
  { emoji: "🌙", text: "Before you sleep, count what went right. The list is always longer than you think.", category: "Serene" },
  { emoji: "🕊️", text: "The present moment, fully inhabited, is always enough.", category: "Serene" },
  { emoji: "🌈", text: "Even difficult days carry gifts. Look for them.", category: "Serene" },
  { emoji: "☕", text: "Morning coffee, warm sunlight, the chance to begin — these are riches.", category: "Serene" },
  { emoji: "🌿", text: "Abundance begins the moment you stop counting what's missing.", category: "Serene" },
  { emoji: "✨", text: "Life rewards those who notice the magic in the mundane.", category: "Serene" },
  { emoji: "🌊", text: "Receive each day like it was made specifically for you. Because it was.", category: "Serene" },
  { emoji: "🎁", text: "Today holds something you haven't discovered yet. Go find it.", category: "Serene" },
  { emoji: "🌟", text: "A grateful mind is a magnet for miracles.", category: "Serene" },
  { emoji: "🌷", text: "Bloom where you are planted. And be grateful for the soil.", category: "Serene" },
  { emoji: "🌤️", text: "Every morning your lungs fill with air. Start there. Start with awe.", category: "Serene" },
  { emoji: "🦋", text: "You have been given the extraordinary privilege of a new day. Honour it.", category: "Serene" },
];

export function getQuoteForMindset(mindset?: string): Quote {
  let category: "Vibrant" | "Steady" | "Serene";
  if (mindset === "Creative Fire" || mindset === "Unstoppable Confidence" || mindset === "Vitality Rush") {
    category = "Vibrant";
  } else if (mindset === "Zen Focus") {
    category = "Steady";
  } else {
    category = "Serene";
  }
  const pool = QUOTES.filter((q) => q.category === category);
  const dayIndex = Math.floor(Date.now() / 86400000);
  return pool[dayIndex % pool.length];
}
